apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "frontend-static-ip" # 고정 IP 이름
    cert-manager.io/cluster-issuer: "letsencrypt-prod" # HTTPS 인증서 발급 시 사용
spec:
  rules:
  - host: mail-cote.site   # 도메인 이름
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 80
  tls:
  - hosts:
    - mail-cote.site
    secretName: mail-cote-tls-secret # HTTPS 인증서 정보
