apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend-service
  ports:
  - protocol: TCP
    port: 80             # 외부 요청을 받을 포트
    targetPort: 8501     # 컨테이너 내부 포트
  type: ClusterIP         # 클러스터 내부 통신
