apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
 name: frontend-config
spec:
 redirectToHttps:
   enabled: true  # HTTP -> HTTPS 리다이렉트 활성화
   responseCodeName: PERMANENT_REDIRECT

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "frontend-ip"
    networking.gke.io/managed-certificates: "frontend-ip-cert"
    networking.gke.io/frontend-config: "frontend-config"
  labels:
    app: frontend-service
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - mail-cote.site
      secretName: mail-cote-tls
  rules:
    - host: mail-cote.site
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 80